#!/usr/bin/with-contenv bash

VERSION_FILE='/octoprint/octoprint/.CONTAINER_VERSION'

# Test if file exists
# If yes, check if contents equal current version
# If either are NO, run pip check...

pip check
